# netlify.toml
# Netlify用設定ファイル

[build]
  # ビルドコマンド（静的サイトの場合は不要）
  command = ""
  # 公開ディレクトリ
  publish = "."

# リダイレクト設定（必要に応じて）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# セキュリティヘッダー（_headersファイルと併用）
[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self';"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), gyroscope=(), magnetometer=(), payment=()"

# 画像ファイルのキャッシュ設定
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# HTMLファイルのキャッシュ設定
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"